export const services = [
  {
    name: "Event Management",
    title: "LIVE EVENT PRODUCTION AND LOGISTICS MANAGEMENT",
    banner: "event.png",
    des: "We take care of everything required to produce your event from planning to execution, including creative design. Based on the years of experience in Esports production, we can create and design any creative model needed for your event, mainstages, player tables, caster set, etc.",
    content: [
      "Program Design",
      "Floor Plan",
      "Equipment Leasing",
      "Scenography And Furniture",
      "Venue/Vendor Sourcing & Negotiation",
      "Crew, Staff, & Player Logistics",
    ],
  },
  {
    name: "Broadcast Management",
    title: "BROADCAST PRODUCTION",
    banner: "service_broadcast.png",
    des: "Specialized in gaming and esports broadcast, on-site and off-site",
    content: [
      "Talent Recluitment",
      "Integration Graphic Team",
      "In-House Design",
      "Specialized In-Game Observers",
      "Live And Remote Broadcast Operation",
      "Encoding And Content Distribution",
    ],
  },
  {
    name: "Specialized Infrastructure",
    title: "SPECIALIZED INFRASTRUCTURE AND SUPPORT",
    banner: "service_infrastructure.png",
    des: "After tons of tournament events and LANs, we have the know-how of the international major competitions to setup your tournaments and give the correct tech support and trouble shooting to any situation that may happen.",
    content: [
      "Competitive Set-Ups",
      "Live Tech Support",
      "IT Platform And Solutions",
    ],
  },
  {
    name: "Competitive Management",
    title: "COMPETITIVE AND SPORTS MANAGEMENT",
    banner: "service_competitive.png",
    des: "We design your competition based on the specific needs of your project, from community tournaments to profesional leagues.",
    content: [
      "Esports League",
      "Competitive Model Design",
      "Data Science Applied on Esports",
      "Prize Payment Management",
      "Player & Teams Bootcamp",
      "Statistics and Data Management",
      "Ruleset Design",
      "Esports Consulting",
    ],
  },
  {
    name: "Social Media Management",
    title: "SOCIAL MEDIA MANAGEMENT",
    banner: "service_social.png",
    des: "Management of any platform required with their custom diversification content based on the community likes and trends.",
    content: [
      "Creation Of Esports & Gaming Content For Social Media",
      "Coordination And Management of Influencers",
      "Customized Landing Page Design And Development",
      "Identity Development",
      "Content Planification & Creation",
      "Post Production Design And Animation",
    ],
  },
  {
    name: "Player Management",
    title: "PLAYER MANAGEMENT",
    banner: "service_player.png",
    des: "We assist the players and help them to coordinate with your production needs. Our team being former pro-players also know the requirements of the competitors.",
    content: [
      "Travel, Lodging and COVID Testing Assistance",
      "Personalized Assistance to Competitors",
      "Player Management for Rehearsal and Competition",
      "Follow-up of Agenda, Interviews, Photoshoot and Content",
      "Competition Workflow Guidance",
      "Issue Tracking & Follow Up",
    ],
  },
];
